version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: mechama
      POSTGRES_PASSWORD: mechama123
      POSTGRES_DB: mechama
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  backend:
    build: .
    command: npm run start:dev
    volumes:
      - .:/app
    working_dir: /app/backend
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=mechama
      - POSTGRES_PASSWORD=mechama123
      - POSTGRES_DB=mechama
      - JWT_SECRET=supersecretjwtkey
      - JWT_EXPIRES_IN=3600s
      - PORT=3001
    ports:
      - '3001:3001'
    depends_on:
      - postgres
      - redis
      - rabbitmq

volumes:
  pgdata: